# This is a basic workflow to help you get started with Actions

name: Arduino_CI_ESP32

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - test compiling examples
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: arduino/setup-arduino-cli@v1.1.1
      - uses: ArminJo/arduino-test-compile@v3.0.0
        with:
          sketch-names-find-start: examples
          arduino-board-fqbn: esp32:esp32:esp32
          platform-default-url: https://dl.espressif.com/dl/package_esp32_index.json
          required-libraries: PubSubClient, home-assistant-integration
